#pragma once

using namespace ATL;

template <class T>
class CProxy_IDataProviderEvents : public IConnectionPointImpl<T, &__uuidof( _IDataProviderEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
