#pragma once
#include "../Utilities/ComUtilities.h"

using namespace ATL;

template <class T>
class CProxy_IGPUTempDataEvents : public IConnectionPointImpl<T, &__uuidof( _IGPUTempDataEvents ), CComDynamicUnkArray>
{
    // WARNING: This class may be regenerated by the wizard
public:
    using TBase = IConnectionPointImpl<T, &__uuidof(_IGPUTempDataEvents), CComDynamicUnkArray>;

    void Fire_OnNextSample(float value)
    {
        const auto pThis = static_cast<T*>(this);

        CComUtilities::FireEvent(pThis, TBase::m_vec, 0x1, value);
    }
};
