<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="DataSrvLib">
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>91a7732c-78ba-49c0-a70b-72775c343a6f</Guid>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="WPF-UI" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
  </ItemGroup>

</Project>
